services:
  - type: web
    name: ouwn
    env: python
    branch: main
    buildCommand: pip install --user -r requirements.txt
    startCommand: gunicorn ouwn_website.app:app
    envVars:
      - key: FIREBASE_KEY
        fromSecret: FIREBASE_KEY
      - key: EMAIL_PASSWORD
        fromSecret: EMAIL_PASSWORD
